version: "3"

services:
  webserver:
    build: 
      context: ./docker/web
    container_name: 'webserver'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    environment:
      - http_proxy=http://mitmproxy:8080
      - HTTPS_PROXY=https://mitmproxy:8080
    command: bash -c "update-ca-certificates --verbose && apache2-foreground"
    links:
      - mitmproxy
    volumes: 
      - ./www:/var/www/html
      - ./configs/web/vhosts:/etc/apache2/sites-enabled/
      - ./configs/php/php.ini:/usr/local/etc/php/php.ini
      - mitm-volume:/usr/local/share/ca-certificates/extra/
  mitmproxy:
    build:
      context: ./docker/mitmproxy
    command: mitmweb --web-host 0.0.0.0
    ports:
      - "8080:8081" 
    tty: true
    volumes:
      - mitm-volume:/home/mitmproxy/.mitmproxy/
volumes:
  mitm-volume:
